### ISSUE TITLE
"No overload matches this call, Property children does not exist on type..." 

### ISSUE THREAD

**Issue by m0nm** [felipecarrillo100/react-bootstrap-submenu#12]
You should add children type in the Props interface for both components

**Comment by animusna** [comment]
I report the same problem using TypeScript.
The problem is not present when TypeScript is not used.

**Comment by felipecarrillo100** [comment]
The issue is in react-bootstrap 2.x.x
There is a breaking change in 2.x.x   react-bootstrap-submenu library is compatible with react-bootstrap 1.x.x

If you can downgrade your bootstrap to 1.x.x you can work around this issue.  I will update for compatibility with react-bootstrap 2.x.x when I have some time
