### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by studiocodeur** [felipecarrillo100/react-bootstrap-submenu#4]
Hi there,

After npm install i receive the following error. 

error - ./node_modules/react-bootstrap-submenu/src/index.css
Global CSS cannot be imported from within node_modules.

After uncommenting the css import. It works.

**Comment by felipecarrillo100** [comment]
Hi,  when I wrote this code I assumed users would use a CSS/SCSS loader/plugin. Apparently you don't use one.
  
If you use tools such as  Webpack you are able to import CSS directly in your JS code.  
Can you add a CSS loader to your project, this would solve your issue?  

Otherwise, I believe there is a guy who made a fork of my code because he had the same issue as you.  You could use his fork instead on my code. 

Look at the fork from RIPT1DE/react-bootstrap-submenu

If I do a new version in the future I will do the change as well, but for now I don't have much free time.

Best regards

**Comment by marcosvspimenta** [comment]
@studiocodeur  Did you do anything besides using forked?

**Comment by raoulguillermo** [comment]
@marcosvspimenta i just uncommented the css import.
