### ISSUE TITLE
Unable to apply custom CSS to the <DropdownSubMenu> on mouse hover 

### ISSUE THREAD

**Issue by syednoman84** [felipecarrillo100/react-bootstrap-submenu#8]
First of all, thanks for sharing this project. It really does the job very easily.

I am actually trying to apply following CSS on mouse hover to the **DropdownSubMenu** but it doesn't use my provided CSS. Below is how my tag look like:

`<DropdownSubmenu title="My Submenu" id="nav-dropdown-submenu">`

And this is the CSS I am providing to it in my App.css file:

```
#nav-dropdown-submenu:hover {
  background-color: red;
  color: white;
}
```

Just for reference purpose, I provide the css for the mouse-hover for **<NavDropdown.Item>** of react-bootstrap and it works perfectly fine but I dont know why it doesn't work for **DropdownSubMenu**
I would appreciate if you can help in solving this. I am sure it must be some basic mistake I might be doing but any help would be great. Thanks

**Comment by felipecarrillo100** [comment]
First, you are assigning an id to a react componet.  React components are not real html components,  they only exist in the virtual dom. They will be converted into real html elements at run time.  That said, I don't think I use id in the props. Since I don't use id, then no id is copied to the real html element.  So, if you look at the real dom you will not find any element with that id.  You could fork the project and make sure the id is placed in a real html element, then your css will work. Not sure why you want to style on id. You should better style on a class.  That would be much easier and makes more sense.

**Comment by felipecarrillo100** [comment]
I added passing id in props for DropdownSubmenu  and MenuItem in   
"react-bootstrap-submenu": "1.0.3",
Now if you pass an id  to the component this will be copied to real dom elements.

**Comment by syednoman84** [comment]
> First, you are assigning an id to a react componet. React components are not real html components, they only exist in the virtual dom. They will be converted into real html elements at run time. That said, I don't think I use id in the props. Since I don't use id, then no id is copied to the real html element. So, if you look at the real dom you will not find any element with that id. You could fork the project and make sure the id is placed in a real html element, then your css will work. Not sure why you want to style on id. You should better style on a class. That would be much easier and makes more sense.

Thank you so much for pointing me to the right direction of using className instead of id. It actually worked based on your explanation.
